[package]
name = "nannou-art-tutes"
version = "0.1.0"
authors = ["Derek Anderson <derek.anderson@virtustream.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou="0.11"
rand="0.7.2"
